lp_website/backoffice/api/urls.py
from django.conf.urls import include, patterns, url
from backoffice.api import views

urlpatterns = patterns('',
    url(r'^get_user_schoolclasses/$', views.get_user_schoolclasses, name='api_get_user_schoolclasses'),
    url(r'^delete_school_class/$', views.delete_school_class, name='api_delete_school_class'),
    url(r'^get_all_classes_students/$', views.get_all_classes_students, name='api_get_all_classes_students'),
    url(r'^delete_user/$', views.delete_user, name='api_delete_user'),
    url(r'^get_schoolclass_administrators/(?P<class_id>\d+)/$', views.get_schoolclass_administrators, name="api_get_schoolclass_administrators"),
    url(r'^remove_administrator/$', views.remove_administrator, name="api_remove_administrator"),
    url(r'^add_administrator/$', views.add_administrator, name="api_add_administrator"),
    url(r'^get_statistics/', include(patterns('',
        url(r'^(?P<class_id>\d+)/(?P<student_id>-?\d+)/$', views.get_statistics, name='api_get_statistics'),
        url(r'^(?P<ref>[\w-]+)/(?P<student_id>\d+)/$', views.get_exercise_statistics, name='api_get_exercise_statistics'),
    ))),
    url(r'^get_subjects/$', views.get_subjects, name="api_get_subjects"),
    url(r'^get_exercises/$', views.get_exercises, name="api_get_exercises"),
    url(r'^get_subjects_exercices/$', views.get_subjects_exercices, name="api_get_subjects_exercices"),
    url(r'^save_subject_config/', include(patterns('',
        url(r'^$', views.save_subject_config, name="api_save_subject_config"),
        url(r'^(?P<subject_config_id>\d+)/$', views.save_subject_config, name="api_update_subject_config"),
    ))),
    url(r'^save_exercise_config/', include(patterns('',
        url(r'^$', views.save_exercise_config, name="api_save_exercise_config"),
        url(r'^(?P<exercise_config_id>\d+)/$', views.save_exercise_config, name="api_update_exercise_config"),
    ))),
    url(r'^get_configurations/$', views.get_configurations, name="api_get_configurations"),
    url(r'^delete_exercise_configuration/$', views.delete_exercise_configuration, name="api_delete_exercise_configuration"),
    url(r'^delete_subject_configuration/$', views.delete_subject_configuration, name="api_delete_subject_configuration"),
)

lp_website/backoffice/urls.py
from django.conf.urls import include, patterns, url
from backoffice import views

urlpatterns = patterns('',
    url(r'^api/', include('backoffice.api.urls'), name='api'),
    url(r'^restapi/', include('backoffice.restapi.urls'), name='restapi'),
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^teachers_required/$', views.teachers_required, name='teachers_required'),
    url(r'^my_classes/$', views.my_classes, name='my_classes'),
    url(r'^edit_class/', include(patterns('',
    	url(r'^$', views.edit_class, name='create_class'),
    	url(r'^(?P<id>\d+)/$', views.edit_class, name='edit_class'),
    ))),
    url(r'^my_students/', include(patterns('',
        url(r'^$', views.my_students, name='my_students_default'),
        url(r'^(?P<class_id>\d+)/$', views.my_students, name='my_students'),
    ))),
    url(r'^edit_student/(?P<class_id>\d+)/', include(patterns('',
        url(r'^$', views.edit_student, name='create_student'),
        url(r'^(?P<id>\d+)/$', views.edit_student, name='edit_student'),
    ))),
    url(r'^class_administrators/(?P<class_id>\d+)/', views.class_administrators, name='class_administrators'),
    url(r'^edit_profile/$', views.edit_profile, name='edit_profile'),
    url(r'^view_profile/(?P<user_id>\d+)/$', views.view_profile, name='view_profile'),
    url(r'^statistics/$', views.statistics, name='statistics'),
    url(r'^raw_statistics/$', views.raw_statistics, name='raw_statistics'),
    url(r'^configuration/', include(patterns('',
        url(r'^$', views.configuration, name='configuration'),
        url(r'^subject/(?P<subject_id>\d+)/$', views.subject_configuration, name='subject_configuration'),
        url(r'^exercise/(?P<exercise_id>\d+)/$', views.exercise_configuration, name='exercise_configuration'),
    ))),
    url(r'^my_configurations/$', views.my_configurations, name='my_configurations'),
)

lp_website/lp_website/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = patterns('',
                       url(r'^', include('website.urls', namespace='website')),
                       url(r'^backoffice/', include('backoffice.urls', namespace='backoffice')),
                       url(r'^admin/', include(admin.site.urls)),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lp_website/website/urls.py
from django.conf.urls import patterns, url
from website import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='website-index'),
)

lp_website/backoffice/api/views.py
# -*- coding: UTF-8 -*-
## @package api
# API de la partie backoffice\n
# Il est nécessaire d'être un utilisateur authentifié de type 'teacher' pour utiliser cette API\n
# Les réponses sont au format JSON
import json
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from rest_framework.renderers import JSONRenderer
from rest_framework import status
from rest_framework.response import Response
from backoffice.decorators import anonymous_required, teacher_required
from backoffice.models import LPUser, SchoolClass, Statistics, Subject, Exercise, SubjectConfig, ExerciseConfig
from backoffice.api.serializers import LPUserSerializer, SchoolClassSerializer, StatisticsSerializer, SubjectSerializer, SubjectConfigSerializer, ExerciseSerializer, ExerciseConfigSerializer
from pprint import pprint

## Classe JSONResponse\n
# Génère une réponse de type JSON\n
# Utilisé pour générer les réponses de l'API
class JSONResponse(HttpResponse):
    def __init__(self, data, **kwargs):
        content = JSONRenderer().render(data)
        kwargs['content_type'] = 'application/json'
        super(JSONResponse, self).__init__(content, **kwargs)

## get_user_schoolclasses\n
# Requête GET
# @returns Toutes les classes dont l'utilisateur loggé est un administrateur
@login_required
@teacher_required
def get_user_schoolclasses(request):
    user = request.user.LPUser
    classes = user.school_class.all().order_by('name')
    serializer = SchoolClassSerializer(classes, many=True)
    return JSONResponse(serializer.data)

## delete_school_class\n
# Supprimer une classe\n
# Requête POST
# @param class_id ID de la classe à supprimer
# @returns Une erreur 400 si la classe n'existe pas, sinon un json confirmant la suppression
@login_required
@teacher_required
def delete_school_class(request):
    post = json.loads(request.body)
    if 'class_id' in post:
        try:
            SchoolClass.objects.get(id=post['class_id']).delete()
        except SchoolClass.DoesNotExist:
            return HttpResponse(status=400)
        response = {}
        response['result'] = 'success'
        response['deleted'] = post['class_id']
    else:
        return HttpResponse(status=400)
    return JSONResponse(json.dumps(response))

## get_all_classes_students\n
# Requête GET
# @returns Toutes les classes liées au professeur ainsi que les élèves dans chaque classe
@login_required
@teacher_required
def get_all_classes_students(request):
	user = request.user.LPUser
	school_classes = user.school_class.all().order_by('name')
	school_class_serializer = SchoolClassSerializer(school_classes, many=True)
	response = {}
	response['school_classes'] = school_class_serializer.data
	response['students'] = {}
	for school_class in school_classes:
		user_serializer = LPUserSerializer(school_class.lpuser_set.filter(user__groups__name__in=['students']).order_by('user__username'), many=True)
		response['students'][school_class.id] = user_serializer.data
	return JSONResponse(json.dumps(response))


## delete_user\n
# Supprimer un utilisateur\n
# Requête POST
# @param user_id ID de l'utilisateur à supprimer
# @returns Une erreur 400 si l'utilisateur n'existe pas, sinon un json confirmant la suppression
@login_required
@teacher_required
def delete_user(request):
    post = json.loads(request.body)
    if 'user_id' not in post:
        return HttpResponse(status=400)
    user_id = post['user_id']
    response = {}
    try:
        lp_user = LPUser.objects.get(id=user_id)
        lp_user.user.delete()
        lp_user.delete()
    except LPUser.DoesNotExist:
        return HttpResponse(status=400)
    response['result'] = 'success'
    response['deleted'] = user_id
    return JSONResponse(json.dumps(response))

## get_schoolclass_administrators\n
# Récupérer la liste des administrateurs pour une classe donnée\n
# Requête GET
# @param class_id ID de la classe
# @returns Une erreur 400 si la classe n'existe pas, sinon la liste des administrateurs associés à la classe
@login_required
@teacher_required
def get_schoolclass_administrators(request, class_id):
    try:
        school_class = SchoolClass.objects.get(id=class_id)
    except SchoolClass.DoesNotExist:
        return HttpResponse(status=400)
    administrators = school_class.lpuser_set.filter(user__groups__name__in=['teachers']).order_by('user__username')
    response = LPUserSerializer(administrators, many=True).data
    return JSONResponse(json.dumps(response))

## remove_administrator\n
# Retirer les droits d'administrateur d'un utilisateur sur une classe\n
# Requête POST
# @param class_id ID de la classe
# @param administrator_id ID de l'administrateur
# @returns Une erreur 400 si la classe n'existe pas ou si l'utilisateur n'en est pas administrateur, sinon un json confirmant la suppression
@login_required
@teacher_required
def remove_administrator(request):
    post = json.loads(request.body)
    if 'class_id' not in post or 'administrator_id' not in post:
        return HttpResponse(status=400)
    class_id = post['class_id']
    administrator_id = post['administrator_id']
    response = {}
    try:
        LPUser.objects.get(id=administrator_id).school_class.remove(SchoolClass.objects.get(id=class_id))
    except (LPUser.DoesNotExist, SchoolClass.DoesNotExist):
        return HttpResponse(status=400)
    response['result'] = 'success'
    response['removed'] = administrator_id
    response['class_id'] = class_id
    if request.user.id == administrator_id:
        response['needRedirect'] = reverse('backoffice:my_classes')
    return JSONResponse(json.dumps(response))

## add_administrator\n
# Ajouter un administrateur à une classe\n
# Requête POST
# @param class_id ID de la classe
# @param username Username de l'utilisateur à ajouter en administrateur
# @returns Une erreur 400 si la classe ou l'utilisateur n'existe pas, sinon un json confirmant la suppression
@login_required
@teacher_required
def add_administrator(request):
    post = json.loads(request.body)
    if 'class_id' not in post or 'username' not in post:
        return HttpResponse(status=400)
    response = {}
    try:
        user = LPUser.objects.filter(user__groups__name__in=['teachers']).get(user__username=post['username'])
        if user.school_class.filter(id=post['class_id']).exists():
            return HttpResponse(status=400)
        school_class = SchoolClass.objects.get(id=post['class_id'])
        user.school_class.add(school_class)
        response['result'] = 'success'
        response['added_administrator'] = LPUserSerializer(user).data
    except (LPUser.DoesNotExist, SchoolClass.DoesNotExist):
        return HttpResponse(status=400)
    return JSONResponse(json.dumps(response))

## get_statistics\n
# Recuperer les statistiques associees a un eleve ou une classe\n
# Requête GET
# @param class_id ID de la classe
# @param student_id Id de l'utilisateur
# @returns Les statistiques de l'utilisateur ou les statistiques de la classe si student_id == -1
@login_required
@teacher_required
def get_statistics(request, class_id, student_id):
    class_id = int(class_id)
    student_id = int(student_id)
    stats = None
    if student_id == -1:
        stats = Statistics.objects.filter(user__school_class__id__in=[class_id]).order_by('user__user__username', 'date')
    else:
        stats = Statistics.objects.filter(user__id__in=[student_id]).order_by('date')
    response = StatisticsSerializer(stats, many=True).data
    return JSONResponse(json.dumps(response))

## get_exercise_statistics\n
# Recuperer les statistiques d'un eleve pour un exercice donné\n
# Requête GET
# @param ref Reference de l'exercice
# @param student_id Id de l'utilisateur
# @returns Les statistiques de l'utilisateur pour l'exercice donné
@login_required
@teacher_required
def get_exercise_statistics(request, ref, student_id):
    student_id = int(student_id)
    stats = Statistics.objects.filter(user__id__in=[student_id], exercise__reference__in=[ref]).order_by('-date')
    response = StatisticsSerializer(stats, many=True).data
    return JSONResponse(json.dumps(response))

## get_subjects\n
# Requête GET
# @returns Toutes les matieres scolaires
@login_required
@teacher_required
def get_subjects(request):
    subjects = Subject.objects.all().order_by('name')
    serializer = SubjectSerializer(subjects, many=True)
    return JSONResponse(serializer.data)

## get_exercises\n
# Requête GET
# @returns Tous les exercices
@login_required
@teacher_required
def get_exercises(request):
    exercises = Exercise.objects.all().order_by('subject__name', 'name')
    serializer = ExerciseSerializer(exercises, many=True)
    return JSONResponse(serializer.data)

## get_subjects_exercices\n
# Requête GET
# @returns Tous les exercices associés à leur matiere correspondante
@login_required
@teacher_required
def get_subjects_exercices(request):
    response = {}
    subjects = Subject.objects.all().order_by('name')
    subjects_serializer = SubjectSerializer(subjects, many=True)
    response['subjects'] = subjects_serializer.data
    exercises = Exercise.objects.all().order_by('subject__name', 'name')
    exercises_serializer = ExerciseSerializer(exercises, many=True)
    response['exercises'] = exercises_serializer.data
    return JSONResponse(json.dumps(response))

## save_subject_config\n
# Sauvegarder une nouvelle configuration ou modifier une configuration existante\n
# Requête POST
# @param subject_config_id ID de la configuration dans le cas de la modification d'une configuration deja existante
# @param config_name Nom de la configuration
# @param school_class Classe associée
# @param subject_id Matiere associée
# @param data Données de configuration
# @returns Une erreur 400 si la matiere, la classe ou la configuration n'existent pas. Sinon un json confirmant la sauvegarde
@login_required
@teacher_required
def save_subject_config(request, subject_config_id=None):
    post = json.loads(request.body)

lp_website/backoffice/templates/backoffice/configuration.html
{% extends "backoffice/layout.html" %}
{% load bootstrap3 %}


{% block title %}Personnalisation{% endblock title %}

{% block navbar_configuration %}active{% endblock navbar_configuration %}

{% block content %}
<div ng-controller="ConfigurationCtrl">

  <div class="alert alert-danger alert-dismissible" role="alert" ng-show='alertError'>
      <button type="button" class="close" ng-click="alertError=false"><span aria-hidden="true">&times;</span></button>
      {%verbatim%}{{alertErrorMessage}}{%endverbatim%}
  </div>

  {% if not edit_mode %}
  <div class="row">
    <div class="col-xs-6 col-sm-4">
      <select class="form-control"
        ng-model="selectedConfigType"
        ng-options="type for type in configTypes">
      </select>
    </div>
    <div class="col-xs-6 col-sm-4">
      <select class="form-control"
        ng-if="selectedConfigType == 'Exercice'"
        ng-model="select.selectedExercise"
        ng-options="(exercise.subject + ' - ' + exercise.name) for exercise in exercises">
      </select>
      <select class="form-control"
        ng-if="selectedConfigType == 'Matière'"
        ng-model="select.selectedSubject"
        ng-options="subject.name for subject in subjects">
      </select>
    </div>
    <div class="col-xs-6 col-sm-4">
      <button class="btn btn-primary" ng-click="prepareForm()">Personnaliser</button>
    </div>
  </div>
  {% else %}
  <a href="{% url 'backoffice:my_configurations' %}">< Mes personnalisations</a>
  <div id="edit_config_data" data-type="{{data_type}}" data-config-base="{{data_config_base}}" data-config-custom="{{data_config_custom}}" style="display: none;"></div>
  {% endif %}

  <div class="config-container">
    <div class="alert alert-warning alert-dismissible" role="alert" ng-show='alertWarning'>
      <button type="button" class="close" ng-click="alertWarning=false"><span aria-hidden="true">&times;</span></button>
      {%verbatim%}{{alertWarningMessage}}{%endverbatim%}
    </div>
    <div class="alert alert-success alert-dismissible" role="alert" ng-show='alertSuccess'>
      <button type="button" class="close" ng-click="alertSuccess=false"><span aria-hidden="true">&times;</span></button>
      {%verbatim%}{{alertSuccessMessage}}{%endverbatim%}
    </div>
    <div>
      <form name="configurationForm" sf-schema="schema" sf-form="form" sf-model="model" ng-submit="onSubmit(configurationForm, select)"></form>
    </div>
  </div>
</div>
{% endblock content %}

lp_website/backoffice/templates/backoffice/edit_class.html
{% extends "backoffice/layout.html" %}
{% load bootstrap3 %}


{% block title %}{% if school_class %}Editer une classe{% else %}Créer une classe{% endif %}{% endblock title %}

{% block navbar_my_classes %}active{% endblock navbar_my_classes %}

{% block content %}
<a href="{% url 'backoffice:my_classes' %}">< retour à mes classes</a>
<form role="form" id="class_form" method="post" action="{% if school_class %}{% url 'backoffice:edit_class' id=school_class.id %}{% else %}{% url 'backoffice:create_class' %}{% endif %}">
  {% csrf_token %}
  <div class="form-group">
    <div class="row">
      <div class="col-lg-offset-3 col-lg-6">
	{% bootstrap_form class_form %}
      </div>
    </div>
  </div>
  {% buttons %}
  <div class="row">
    <div class="col-lg-offset-3 col-lg-6">
      <button type="submit" name="submit" class="btn btn-primary">{% if school_class %}Sauvegarder les modifications{% else %}Créer la classe{% endif %}</button>
    </div>
    {% endbuttons %}
</form>
{% endblock content %}

lp_website/backoffice/templates/backoffice/edit_profile.html
{% extends "backoffice/layout.html" %}
{% load bootstrap3 %}

{% block title %}Mon profil{% endblock title %}

{% block content %}
<img class="centered-image large-avatar"src="{{ lp_user.avatar.url }}">
<form role="form" id="profile-form" method="post" action="{% url 'backoffice:edit_profile' %}" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="form-group">
    <div class="row">
      <div class="col-lg-offset-3 col-lg-6">
  {% bootstrap_form avatar_form %}
  {% bootstrap_form email_form %}
  {% bootstrap_form password_form %}
      </div>
    </div>
  </div>
  {% buttons %}
  <div class="row">
    <div class="col-lg-offset-3 col-lg-6">
      <button type="submit" name="submit" class="btn btn-primary">Sauvegarder les modifications</button>
    </div>
  </div>
  {% endbuttons %}
</form>
{% endblock content %}

lp_website/backoffice/templates/backoffice/edit_student.html
{% extends "backoffice/layout.html" %}
{% load bootstrap3 %}


{% block title %}{% if student %}Editer un élève{% else %}Créer un élève{% endif %}{% endblock title %}

{% block navbar_my_students %}active{% endblock navbar_my_students %}

{% block content %}
<img class="centered-image large-avatar"src="{{ student.avatar.url }}">
<form role="form" id="student-form" method="post" action="{% if student %}{% url 'backoffice:edit_student' class_id=school_class.id id=student.id %}{% else %}{% url 'backoffice:create_student' class_id=school_class.id %}{% endif %}" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="form-group">
    <div class="row">
      <div class="col-lg-offset-3 col-lg-6">
  {% bootstrap_form avatar_form %}
  {% bootstrap_form student_form %}
      </div>
    </div>
  </div>
  {% buttons %}
  <div class="row">
    <div class="col-lg-offset-3 col-lg-6">
      <button type="submit" name="submit" class="btn btn-primary">{% if student %}Sauvegarder les modifications{% else %}Créer l'élève{% endif %}</button>
    </div>
  </div>
  {% endbuttons %}
</form>
{% endblock content %}

lp_website/backoffice/templates/backoffice/index.html
{% extends "backoffice/layout.html" %}

{% block title %}Backoffice{% endblock title %}

{% block navbar_home %}active{% endblock navbar_home %}

{% block content %}
<p>Bienvenue, {{ user.username }}.</p>
{% endblock content %}

lp_website/backoffice/templates/backoffice/layout.html
{% extends "backoffice/base.html" %}

{% block page-content %}
<div class="wrapper">
  <header class="main-header">
    <a href="/" class="logo">Learn & Play</a>
    <nav class="navbar navbar-static-top" role="navigation">
      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <img src="{{ user.LPUser.avatar.url }}" class="user-image" alt="User Image"/>
              <span class="hidden-xs">{{ user.username }}</span>
            </a>
            <ul class="dropdown-menu">
              <li class="user-header">
                <img src="{{ user.LPUser.avatar.url }}" class="img-circle" alt="User Image" />
                <p>{{ user.username }}</p>
              </li>
              <li class="user-footer">
                <div class="pull-left">
                  <a href="{% url 'backoffice:edit_profile' %}" class="btn btn-default btn-flat">Profil</a>
                </div>
                <div class="pull-right">
                  <a href="{% url 'backoffice:logout' %}" class="btn btn-default btn-flat">Déconnexion</a>
                </div>
              </li>
            </ul>
          </li>
        </ul>
      </div>

    </nav>
  </header>

  <aside class="main-sidebar">
    <section class="sidebar">
      <ul class="sidebar-menu">
        <li class="header">GÉNÉRAL</li>
        <li class="{% block navbar_home %}{% endblock %}"><a href="{% url 'backoffice:index' %}"><span>Accueil</span></a></li>
        <li class="header">ADMINISTRATION</li>
        <li class="{% block navbar_my_classes %}{% endblock %}"><a href="{% url 'backoffice:my_classes' %}"><span>Mes classes</span></a></li>
        <li class="{% block navbar_my_students %}{% endblock %}"><a href="{% url 'backoffice:my_students_default' %}"><span>Mes élèves</span></a></li>
        <li class="header">STATISTIQUES</li>
        <li class="{% block navbar_statistics %}{% endblock %}"><a href="{% url 'backoffice:statistics' %}"><span>Statistiques</span></a></li>
        <li class="{% block navbar_raw_statistics %}{% endblock %}"><a href="{% url 'backoffice:raw_statistics' %}"><span>Statistiques brutes</span></a></li>
        <li class="header">PERSONNALISATION</li>
        <li class="{% block navbar_configuration %}{% endblock %}"><a href="{% url 'backoffice:configuration' %}"><span>Personnalisation</span></a></li>
        <li class="{% block navbar_my_configurations %}{% endblock %}"><a href="{% url 'backoffice:my_configurations' %}"><span>Mes personnalisations</span></a></li>
      </ul>
    </section>
  </aside>

  <div class="content-wrapper">
    <section class="content-header">
    </section>
    <section class="content">
      {% block content %}{% endblock content %}
    </section>
  </div>

  <footer class="main-footer">
    <strong>Copyright &copy; 2015 <a href="/">Learn & Play</a>.</strong> All rights reserved.
  </footer>
</div>
{% endblock page-content %}

lp_website/backoffice/templates/backoffice/login.html
{% extends "backoffice/base.html" %}
{% load bootstrap3 %}

{% block title %}Connexion{% endblock title %}

{% block page-content %}
<h1 class="row">
  <div class="col-lg-offset-3 col-lg-6">
    Formulaire de connexion
  </div>
</h1>
<form role="form" id="login_form" method="post" action="/backoffice/login/">
  {% csrf_token %}
  <div class="form-group">
    <div class="row">
      <div class="col-lg-offset-3 col-lg-6">
	{% bootstrap_form login_form %}
      </div>
    </div>
  </div>
  {% buttons %}
  <div class="row">
    <div class="col-lg-offset-3 col-lg-6">
      <button type="submit" name="submit" class="btn btn-primary">Connexion</button>
    </div>
    {% endbuttons %}
</form>
<div class="row" style="padding-top:2em;">
  <div class="col-lg-offset-3 col-lg-6">
    <a href="{% url 'backoffice:register' %}">Créer un compte</a>
  </div>
</div>
{% endblock page-content %}

lp_website/backoffice/templates/backoffice/my_classes.html
{% extends "backoffice/layout.html" %}
{% load bootstrap3 %}

{% block title %}Mes classes{% endblock title %}

{% block navbar_my_classes %}active{% endblock navbar_my_classes %}

{% block content %}
<div ng-controller="ClassesListCtrl">

    <div class="alert alert-danger alert-dismissible" role="alert" ng-show='alertError'>
        <button type="button" class="close" ng-click="alertError=false"><span aria-hidden="true">&times;</span></button>
        {%verbatim%}{{schoolClassAlertError}}{%endverbatim%}
    </div>

    <div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="confirmation-modal" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    Confirmer la suppression
                </div>
                <div class="modal-body">
                    <p>Vous êtes sur le point de supprimer la classe <strong ng-init="userData.schoolClassToDelete='';">{%verbatim%}{{userData.schoolClassToDelete.name}}{%endverbatim%}</strong>.</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Annuler</button>
                    <button id="confirm-delete-modal" type="button" class="btn btn-danger" ng-click="deleteSchoolClass(userData.schoolClassToDelete);">Supprimer</button>
                </div>
            </div>
        </div>
    </div>
	<table class="table table-striped" ng-show="classes.length!=0">
    	<thead>
        	<tr>
                <th data-field="id">Identifiant</th>
            	<th data-field="name">Classe</th>
            	<th data-field="school">Etablissement</th>
            	<th>Actions</th>
        	</tr>
    	</thead>
    	<tbody>
			<tr ng-repeat="class in classes">
                <td>{%verbatim%}{{class.id}}{%endverbatim%}</td>
				<td>{%verbatim%}{{class.name}}{%endverbatim%}</td>
				<td>{%verbatim%}{{class.school_name}}{%endverbatim%}</td>
				<td>
					<a href="{%verbatim%}{{class.edit_url}}{%endverbatim%}" class="btn btn-xs btn-primary">Editer</a>&nbsp;&nbsp;
					<a href="{%verbatim%}{{class.administrators_url}}{%endverbatim%}" class="btn btn-xs btn-primary">Administrateurs</a>&nbsp;&nbsp;
					<button type="button" class="btn btn-xs btn-danger" data-toggle="modal" data-target="#confirm-delete" ng-click="userData.schoolClassToDelete = class;">Supprimer</button>
				</td>
			</tr>
		</tbody>
	</table>
    <div class="alert alert-danger" role="alert" ng-show="classes.length==0">Votre compte n'est pas encore associé à une classe</div>
</div>

<a class="btn btn-primary" href="{% url 'backoffice:create_class' %}">{% bootstrap_icon "plus" %} Créer une classe</a>
{% endblock content %}

{% block script %}
$("#confirm-delete-modal").on('click', function() {
   $("#confirm-delete").modal("hide");
});
{% endblock script %}